fix: Add a working `cuda` feature
lurk-lab/grumpkin-msm pull request #9
Opened 2024-01-09 00:10 UTC by winston-h-zhang

Resolves https://github.com/lurk-lab/lurk-rs/issues/1030 downstream. This PR adds an actual `cuda` feature that can be toggled `grumpkin-msm`, and thus all of its dependents.

2024-01-09 02:18 UTC, samuelburnham approved these changes

2024-01-09 02:18 UTC, samuelburnham commented on .github/workflows/gpu-ci.yml
> +# Runs the test suite on a self-hosted GPU machine with CUDA enabled
Nit: we're only building here, not testing. Is the latter intended for later or not a priority?

2024-01-09 14:45 UTC, huitseeker requested changes
1. do we really need to push the semantics of the cuda feature inside grumpkin-msm or can we simply not import grumpkin-msm in dependents if that feature is not activated?
2. can we make grumpkin-msm print an **indiscutably spectacular** message if it's loaded and does not manage to resolve to a GPU-using MSM? I really want the fallback to the CPU to be extremely noticeable, 100% of the time, every time.

2024-01-15 16:38 UTC, huitseeker requested changes
To reproduce the comment from https://github.com/lurk-lab/arecibo/issues/259, this is going in a good direction given the fresh benchmarks results, but:

we should make grumpkin-msm:
1/ always compile the CPU method, as it does now,
2/ only attempt to compile and run the GPU method when the cuda feature is enabled
3/ emit an indiscutably spectacular message when it's compiled with the cuda feature and does not find the CPU,

2024-01-23 20:43 UTC, winston-h-zhang commented
This is the error message:
```
paperspace@psrjp5jvivu1:~/lurk-lab/grumpkin-msm$ cargo build --features cuda
   Compiling sppark v0.1.5
   Compiling grumpkin-msm v0.1.0 (/home/paperspace/lurk-lab/grumpkin-msm)
warning: grumpkin-msm@0.1.0: feature "cuda" was enabled but no valid installation of CUDA was found
warning: grumpkin-msm@0.1.0: the crate's default CPU methods will be compiled instead; NO GPU IMPLEMENTATION WILL BE USED WHEN CALLING THIS CRATE'S METHODS
warning: grumpkin-msm@0.1.0: please recompile without feature "cuda" or provide a valid CUDA installation
    Finished dev [unoptimized + debuginfo] target(s) in 2.48s
```

2024-01-23 20:55 UTC, huitseeker approved these changes
Excellent, thanks a lot!

2024-01-23 21:24 UTC, merged